### ISSUE TITLE
tvOS compatibility?

### ISSUE THREAD

**Issue by tomaculum** [BlindDev/PVPMikrotikSSH#1]
Hi,

Would it be possible to make this project compatible to the tvOS platform?

Currently I get this error trying to install the Pod:

    [!] The platform of the target `target-name` (tvOS 11.4) is not compatible with `PVPMikrotikSSH (1.0.4)`, which does not support `tvos`.

Or is there a way to achieve this manually?

**Comment by BlindDev** [comment]
@tomaculum hi. This framework was created only to work with my current project that works on iOS only. I've just shared it. 
I was not going to make any changes or updates so far. So go ahead and copy this framework files to your project and then add the library NMSSH v. 2.2.9 (use pod).
Let me know if it won't work, I'll help

**Comment by tomaculum** [comment]
Alright, thank you! (:
